// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9U37Zhq1EewgIo069mtY3voQg1zGKwDU',
    appId: '1:873299453483:web:aaf1c8bc6c3af78d7d6c6e',
    messagingSenderId: '873299453483',
    projectId: 'trip-organizer-e7056',
    authDomain: 'trip-organizer-e7056.firebaseapp.com',
    storageBucket: 'trip-organizer-e7056.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBofxMn5g_FO_pSeGroNjztNW20TvXv6cI',
    appId: '1:873299453483:android:0ead77c16f5795eb7d6c6e',
    messagingSenderId: '873299453483',
    projectId: 'trip-organizer-e7056',
    storageBucket: 'trip-organizer-e7056.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKRZmkuK4VM215UY1jdcbEJhJkMTKNsZo',
    appId: '1:873299453483:ios:ee4d3c776a3141957d6c6e',
    messagingSenderId: '873299453483',
    projectId: 'trip-organizer-e7056',
    storageBucket: 'trip-organizer-e7056.firebasestorage.app',
    iosBundleId: 'com.example.tripOrganizerProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKRZmkuK4VM215UY1jdcbEJhJkMTKNsZo',
    appId: '1:873299453483:ios:ee4d3c776a3141957d6c6e',
    messagingSenderId: '873299453483',
    projectId: 'trip-organizer-e7056',
    storageBucket: 'trip-organizer-e7056.firebasestorage.app',
    iosBundleId: 'com.example.tripOrganizerProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9U37Zhq1EewgIo069mtY3voQg1zGKwDU',
    appId: '1:873299453483:web:07df27cdc6fc19a77d6c6e',
    messagingSenderId: '873299453483',
    projectId: 'trip-organizer-e7056',
    authDomain: 'trip-organizer-e7056.firebaseapp.com',
    storageBucket: 'trip-organizer-e7056.firebasestorage.app',
  );

}